import React from 'react';
import { View, Text, ScrollView, TouchableOpacity, StyleSheet } from 'react-native';
import { ArrowLeft, ArrowUpRight, Calendar, Mail, CheckCircle2, Circle, MessageSquare, ArrowUp, Search, Shield } from 'lucide-react-native';
import { Card } from '../../components/common/Card';
import { useTheme } from '../../theme/ThemeContext';
export function DesignPreviewScreen({ onBack }: { onBack: () => void }) {
  const { colors: c } = useTheme();
  return <ScrollView style={{ flex: 1, backgroundColor: c.background }} contentContainerStyle={styles.page}>
    <View style={styles.header}><TouchableOpacity onPress={onBack} accessibilityLabel='Back to sign in'><ArrowLeft size={22} color={c.textPrimary}/></TouchableOpacity><Text style={[styles.brand,{color:c.textPrimary}]}>Orbit</Text><View style={[styles.badge,{borderColor:c.border}]}><Text style={{color:c.textSecondary,fontSize:11}}>DESIGN PREVIEW</Text></View></View>
    <Text style={[styles.eyebrow,{color:c.accent}]}>YOUR SPACE, AT A GLANCE</Text>
    <Text style={[styles.title,{color:c.textPrimary}]}>A little less on{ '\n' }your mind.</Text>
    <Text style={[styles.subtitle,{color:c.textSecondary}]}>A calm place for the things you want to keep moving.</Text>
    <Card><View style={styles.row}><View style={[styles.icon,{backgroundColor:c.accentSubtle}]}><Calendar size={20} color={c.accent} strokeWidth={1.6}/></View><View style={{flex:1}}><Text style={[styles.heading,{color:c.textPrimary}]}>Your day</Text><Text style={{color:c.textSecondary,fontSize:12}}>Calendar, without the clutter</Text></View><ArrowUpRight size={18} color={c.textTertiary}/></View><View style={[styles.empty,{borderColor:c.borderSubtle}]}><Text style={{color:c.textSecondary,lineHeight:21}}>Connect Google Calendar to see your real events. Nothing is connected in this preview.</Text></View></Card>
    <Card><View style={styles.row}><Mail size={20} color={c.accent} strokeWidth={1.6}/><Text style={[styles.heading,{color:c.textPrimary,flex:1}]}>Inbox, with context</Text><Text style={{color:c.textTertiary,fontSize:12}}>Read-only</Text></View><Text style={[styles.body,{color:c.textSecondary}]}>Find a message, catch up on a thread, keep the details close. Google setup comes before private inbox access.</Text><View style={[styles.pill,{backgroundColor:c.surfaceSecondary}]}><Shield size={14} color={c.textSecondary}/><Text style={{color:c.textSecondary,fontSize:12}}>Sending is not enabled</Text></View></Card>
    <Card><View style={styles.row}><CheckCircle2 size={20} color={c.accent} strokeWidth={1.6}/><Text style={[styles.heading,{color:c.textPrimary}]}>Small steps, kept together</Text></View>{['Capture an idea','Review a saved note'].map(t=><View key={t} style={[styles.task,{borderColor:c.borderSubtle}]}><Circle size={16} color={c.textTertiary}/><Text style={{color:c.textSecondary}}>{t}</Text><Text style={{marginLeft:'auto',fontSize:10,color:c.textTertiary}}>EXAMPLE</Text></View>)}</Card>
    <Card><View style={styles.row}><MessageSquare size={20} color={c.accent} strokeWidth={1.6}/><Text style={[styles.heading,{color:c.textPrimary}]}>Start with a thought</Text></View><View style={[styles.composer,{backgroundColor:c.inputBackground,borderColor:c.border}]}><Text style={{color:c.textTertiary,flex:1}}>What would make today easier?</Text><View style={[styles.send,{backgroundColor:c.accentSubtle}]}><ArrowUp size={18} color={c.accent}/></View></View><Text style={{color:c.textTertiary,fontSize:12,lineHeight:19,marginTop:12}}>This is a visual preview. No messages, tasks or account changes are sent from this screen.</Text></Card>
    <TouchableOpacity onPress={onBack} style={[styles.back,{borderColor:c.border}]}><Text style={{color:c.textPrimary,fontWeight:'600'}}>Back to sign in</Text><ArrowUpRight size={17} color={c.textSecondary}/></TouchableOpacity>
  </ScrollView>;
}
const styles=StyleSheet.create({page:{padding:24,paddingTop:32,maxWidth:680,width:'100%',alignSelf:'center'},header:{flexDirection:'row',alignItems:'center',gap:12,marginBottom:44},brand:{fontSize:20,fontWeight:'700',flex:1},badge:{borderWidth:1,padding:8,borderRadius:8},eyebrow:{fontSize:11,fontWeight:'700',letterSpacing:1.5,marginBottom:12},title:{fontSize:36,fontWeight:'600',lineHeight:42,letterSpacing:-1.2},subtitle:{fontSize:15,lineHeight:23,marginTop:14,marginBottom:28},row:{flexDirection:'row',alignItems:'center',gap:12},icon:{width:40,height:40,borderRadius:12,alignItems:'center',justifyContent:'center'},heading:{fontSize:16,fontWeight:'600'},empty:{marginTop:20,paddingTop:16,borderTopWidth:1},body:{lineHeight:22,fontSize:14,marginTop:18},pill:{flexDirection:'row',gap:8,alignSelf:'flex-start',alignItems:'center',padding:9,borderRadius:9,marginTop:18},task:{flexDirection:'row',gap:10,alignItems:'center',paddingTop:16,marginTop:16,borderTopWidth:1},composer:{flexDirection:'row',alignItems:'center',padding:12,borderWidth:1,borderRadius:14,marginTop:20},send:{width:32,height:32,borderRadius:10,alignItems:'center',justifyContent:'center'},back:{padding:16,borderRadius:14,borderWidth:1,flexDirection:'row',justifyContent:'space-between',marginBottom:20}});
